# Build the code in a maven-container
FROM maven:3-eclipse-temurin-21 AS maven-build
WORKDIR /opt/app
COPY src ./src
COPY pom.xml ./
RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

# Build the JRE directly in an Alpine container to avoid glibc/musl libc issues
FROM eclipse-temurin:21-alpine AS jre-build
WORKDIR /opt/app
COPY --from=maven-build /opt/app/target/kafka-producer-1.0.0.jar ./
RUN jar xf kafka-producer-1.0.0.jar
RUN jdeps --ignore-missing-deps -q  \
    --recursive  \
    --multi-release 21  \
    --print-module-deps  \
    --class-path 'BOOT-INF/lib/*'  \
    kafka-producer-1.0.0.jar > deps.info
RUN jlink \
    --verbose \
    --add-modules $(cat deps.info) \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /customjre

FROM alpine:3.18
COPY --from=jre-build /customjre /opt/jre
ENV JAVA_HOME=/opt/jre
ENV PATH="$PATH:$JAVA_HOME/bin"

COPY --from=maven-build /opt/app/target/kafka-producer-1.0.0.jar /opt/app.jar
ENTRYPOINT ["java","-jar","/opt/app.jar"]
