# Define the root logger
log4j.rootLogger=DEBUG, stdout

# Set the log level for Kafka and related packages
log4j.logger.kafka=DEBUG, stdout
log4j.logger.kafka.network.authenticator=DEBUG, stdout
log4j.logger.kafka.server.KafkaServer=DEBUG, stdout
log4j.logger.kafka.authorizer.logger=DEBUG, stdout

# Define the appender (stdout)
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %p %t %c: %m%n

# Set the log level for specific Kafka components
log4j.logger.org.apache.kafka.common.security.authenticator=DEBUG, stdout
log4j.logger.org.apache.kafka.common.security.plain.PlainSaslServer=DEBUG, stdout
log4j.logger.org.apache.kafka.common.security.auth=DEBUG, stdout
log4j.logger.org.apache.kafka.common.security.plain=DEBUG, stdout
log4j.logger.org.apache.kafka.common.security.sasl=DEBUG, stdout
log4j.logger.org.apache.kafka.common.security.authenticator.SaslServerAuthenticator=DEBUG

